
[general]
	#The module blacklist of this material.
	moduleBlacklist = []
	#The alternative names of this material.
	alternativeNames = []
	#The byproducts of this material.
	extras = []
	#The model type of the material.
	modelType = "crystal"
	#Should items of this material have the enchanted glow.
	hasEffect = false

